import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { copyFileSync, mkdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';

// Auto-deploy built files to Obsidian Sync vault after production builds
const SYNC_VAULT_PLUGIN = join(
  process.env.HOME || "",
  "Documents/Noteometry/.obsidian/plugins/noteometry"
);

function deployToVault() {
  if (!existsSync(SYNC_VAULT_PLUGIN)) return;
  for (const f of ["main.js", "styles.css", "manifest.json"]) {
    try { copyFileSync(f, join(SYNC_VAULT_PLUGIN, f)); } catch {}
  }
  console.log("Deployed to Obsidian Sync vault");
}

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	deployToVault();
	process.exit(0);
} else {
	await context.watch();
}
